sudo: false

language: php

notifications:
  on_success: never
  on_failure: change

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1
    - WP_VERSION=4.2 WP_MULTISITE=0
    - WP_VERSION=4.1 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=3.9 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - bash/build.sh

install:
  - npm install

script:
    - phpunit
    - npm test

env:
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/simple-map/
    - GH_REF: https://github.com/miya0001/simple-map.git
    - secure: "ZNGMiXE0/uRCdIy2gNGeaQMCMWnsXy643m9U8UlNtOuUmnkrHzAiDeip/C7A/D1HZqaBFN7gILztSeJls6mR0onw1bjL4ex0Zabh0GUTIsg+5DVOvRjLvCGOMKtkHOxdT90x+QDvlTQcWvl4OMEoKrwX11dwtVxo+XG+/7BR2tQ="
